config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}

  root to: 'static#index'

  get :dashboard, to: 'dashboard#index'

  resource :user, only: [:edit, :update]

  resources :todo_lists, path: 'todos' do
    collection do
      get :archived
      get :plan
    end

    member do
      put :sort, constraints: {format: :json}
      put :archive
      put :restore
    end
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  include ItemColorHelper
  extend ItemColorHelper

  enum color: item_colors

  belongs_to :user
  has_many :items, class_name: 'TodoListItem', dependent: :destroy

  scope :sorted, -> { order :position }
  scope :archived, -> { where archived: true }
  scope :active, -> { where archived: false }

  attr_accessor :skip_position_validation
  validates :position, presence: true, uniqueness: {scope: :user_id}, unless: -> { archived || skip_position_validation }
  validates :title, presence: true

  before_validation(on: :create) do
    unless position
      self.position = (user.todo_lists.pluck(:position).max || -1) + 1
    end
  end

  def update_position! after
    old_position = position
    self.position = after ? after.position + 1 : 0

    if position != old_position
      others = user.todo_lists.sorted
      if old_position > position
        others = others.where(position: (position...old_position))
        others.each do |other|
          other.position += 1
          other.skip_position_validation = true
          other.save!
        end
      else
        self.position -= 1
        others = others.where(position: ((old_position + 1)..position))
        others.each do |other|
          other.position -= 1
          other.skip_position_validation = true
          other.save!
        end
      end
    end
    save!
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @new_todo_list = current_user.todo_lists.new
    @todo_lists = current_user.todo_lists.active.sorted
  end

  def plan
    start_time = Time.zone.now.beginning_of_day
    end_time = 6.days.from_now.end_of_day
    todo_lists = current_user.todo_lists.active.sorted
    @todo_lists_by_date = {
      past: todo_lists.where('planned_at < ?', start_time),
      nil => [],
    }
    @todo_lists_by_date.delete(:past) if @todo_lists_by_date[:past].empty?
    (start_time.to_date..end_time.to_date).each {|d| @todo_lists_by_date[d] = []}
    todo_lists
      .where('planned_at IS NULL OR planned_at BETWEEN ? AND ?', start_time, end_time)
      .each do |todo_list|
      @todo_lists_by_date[todo_list.planned_at&.to_date] << todo_list
    end
  end

  def archived
    @todo_lists = current_user.todo_lists.archived.sorted
  end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def edit
    @todo_list = current_user.todo_lists.find params[:id]
  end

  def create
    @todo_list = current_user.todo_lists.new todo_list_params
    if @todo_list.save
      flash.notice = t 'page.todo_list.created.successful'
      redirect_back fallback_location: todo_lists_path
    else
      render :new
    end
  end

  def update
    @todo_list = current_user.todo_lists.find params[:id]
    @todo_list.update_attributes todo_list_params
    if @todo_list.save
      flash.notice = t 'page.todo_list.updated.successful'
      redirect_back fallback_location: todo_lists_path
    else
      render :edit
    end
  end

  def sort
    @todo_list = current_user.todo_lists.find params[:id]
    after_id = params.permit(:after)[:after]
    after = after_id && current_user.todo_lists.find(after_id)
    @todo_list.transaction do
      if params.has_key? :plannedAt
        planned_at = params.permit(:plannedAt)[:plannedAt]
        if planned_at.blank?
          @todo_list.planned_at = nil
        else
          begin
            @todo_list.planned_at = Time.parse planned_at
          rescue ArgumentError
            render json: {status: 400, error: 'Invalid Date'}, status: 400
            return
          end
        end
      end
      @todo_list.update_position! after
    end
    render json: {status: :success}
  end

  def archive
    @todo_list = current_user.todo_lists.find params[:id]
    if @todo_list.archived
      flash.alert = t 'page.todo_list.archive.already'
    else
      @todo_list.archived = true
      if @todo_list.save
        flash.notice = t 'page.todo_list.archive.successful'
      else
        flash.alert = t 'page.todo_list.archive.failed', errors: @todo_list.errors.full_messages.join(',')
      end
    end
    redirect_back fallback_location: todo_lists_path
  end

  def restore
    @todo_list = current_user.todo_lists.find params[:id]
    if @todo_list.archived
      @todo_list.archived = false
      if @todo_list.save
        flash.notice = t 'page.todo_list.restore.successful'
      else
        flash.alert = t 'page.todo_list.restore.failed', errors: @todo_list.errors.full_messages.join(',')
      end
    else
      flash.alert = t 'page.todo_list.restore.already'
    end
    redirect_back fallback_location: archived_todo_lists_path
  end

  def destroy
    @todo_list = current_user.todo_lists.find params[:id]
    if @todo_list.archived
      @todo_list.destroy
      flash.notice = t 'page.todo_list.destroy.successful'
    else
      flash.alert = t 'page.todo_list.destroy.not_archived'
    end
    redirect_back fallback_location: archived_todo_lists_path
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
  def section_title_to_class title
    cls = if title.nil?
      :warning
    elsif title.is_a? Symbol
      case title&.to_sym
        when :past; :danger
        when :not_planned; :warning
      end
    else
      nil
    end

    cls ? "section-#{cls}" : nil
  end

  def grouped_column_classes count
    classes = 'uk-child-width-1-1'
    return classes if count < 2
    classes = "#{classes} uk-child-width-1-2@s"
    return classes if count < 4
    classes = "#{classes} uk-child-width-1-4@m"
  end

  def grouped_sub_column_classes count
    classes = 'uk-child-width-1-1'
    return "#{classes} uk-child-width-1-2@xl" if count >= 4
    return "#{classes} uk-child-width-1-2@l uk-child-width-1-4@xl" if count >= 2
    "#{classes} uk-child-width-1-2@2 uk-child-width-1-4@m uk-child-width-1-5@l uk-child-width-1-6@xl"
  end
end

app/views/todo_lists/_form.slim
- if todo_list.errors.any?
  .uk-alert.uk-alert-danger
    ul.uk-list.uk-list-divider
      - todo_list.errors.full_messages.each do |message|
        li= message

= form_for todo_list, class: 'uk-form-stacked' do |f|
  = form_field f, :title do |key, cls, name|
    = f.text_field key, placeholder: name, class: "uk-input #{cls}"

  = form_field f, :description do |key, cls, name|
    = f.text_area key, placeholder: name, class: "uk-textarea #{cls}"

  .form-row(uk-grid)
    .form-label.empty
    .form-field
      = f.button t('page.actions.save'), type: :submit, class: 'uk-button uk-button-primary'

app/views/todo_lists/_grouped_todo_lists.slim
.uk-grid-small(class=grouped_column_classes(grouped_todo_lists.count) uk-grid)
  - grouped_todo_lists.each do |title, todo_lists|
    div
      .todo-list-section class=section_title_to_class(title)
        header
          h2
            - if title.is_a?(Date) || title.is_a?(Time)
              time(datetime=l(title) title=l(title) uk-tooltip)= l title, format: :weekday
            - elsif title.is_a? String
              = title
            - elsif title.is_a? Symbol
              = t title, scope: 'page.todo_list'
            - else
              = t 'page.todo_list.not_planned'
        .todo-list-section-body
          ul.todo-lists.uk-list(uk-sortable="handle: .uk-sortable-handle#{'; group: todo-lists' if group_sortable}" class=grouped_sub_column_classes(grouped_todo_lists.count) uk-grid)
            - todo_lists.each do |todo_list|
              li
                = render partial: 'todo_lists/todo_list', locals: {todo_list: todo_list, actions: actions}

app/views/todo_lists/_list.slim
- if todo_lists.any?
  ul.todo-lists.uk-grid-small(class='uk-child-width-1-1 uk-child-width-1-2@s uk-child-width-1-4@m uk-child-width-1-6@l' uk-sortable='handle: .uk-sortable-handle' uk-grid)
    - todo_lists.each do |todo_list|
      li
        = render partial: 'todo_list', locals: {todo_list: todo_list, actions: actions}
- else
  p= t 'page.list.empty'

app/views/todo_lists/_quick_add_form.slim
= form_for TodoList.new, class: 'uk-form-stacked' do |f|
  .uk-grid.uk-grid-collapse
    .uk-width-expand
      = f.text_field :title, placeholder: TodoList.human_attribute_name(:title), class: 'uk-input'
    div class='uk-width-1-4@s uk-width-1-6@m'
      = f.button t('page.actions.save'), type: :submit, class: 'uk-button uk-button-primary uk-width-1-1'

app/views/todo_lists/_todo_list.slim
article.todo-list data-todo-list-id=todo_list.id
  header
    .uk-sortable-handle
      span.uk-sortable-handle.uk-margin-small-right uk-icon="table"
    = todo_list.title
    ul.uk-iconnav.uk-align-right
      - if todo_list.planned_at
        li
          span(uk-icon='clock' uk-tooltip title=l(todo_list.planned_at))
      - if actions.include? :edit
        li= link_to '', edit_todo_list_path(todo_list), 'uk-icon': 'file-edit', 'uk-tooltip': '', title: t('page.actions.edit')
      - if actions.include? :archive
        li= link_to '', archive_todo_list_path(todo_list), method: :put, 'uk-icon': 'pull', 'uk-tooltip': '', title: t('page.actions.archive')
      - if actions.include? :restore
        li= link_to '', restore_todo_list_path(todo_list), method: :put, 'uk-icon': 'push', 'uk-tooltip': '', title: t('page.actions.restore')
      - if actions.include? :destroy
        li= link_to '', todo_list_path(todo_list), method: :delete, 'uk-icon': 'trash', 'uk-tooltip': '', title: t('page.actions.destroy')

  - if todo_list.items.any? || !todo_list.description.blank?
    section
      - unless todo_list.description.blank?
        p= todo_list.description

      - if todo_list.items.any?
        ul.todo-list-items
          - todo_list.items.each do |item|
            li.todo-list-item class=('completed' if item.completed)
              = item.description

app/views/todo_lists/archived.slim
= render partial: 'list', locals: {todo_lists: @todo_lists, actions: [:restore, :destroy]}

app/views/todo_lists/edit.slim
= render partial: 'form', locals: {todo_list: @todo_list}

app/views/todo_lists/index.slim
= render partial: 'quick_add_form'

= render partial: 'list', locals: {todo_lists: @todo_lists, actions: [:edit, :archive]}

= link_to t('page.actions.new'), new_todo_list_path, class: 'uk-button uk-button-primary'

app/views/todo_lists/new.slim
= render partial: 'form', locals: {todo_list: @todo_list}

app/views/todo_lists/plan.slim
= render partial: 'quick_add_form'

= render partial: 'grouped_todo_lists', locals: {grouped_todo_lists: @todo_lists_by_date, actions: [:edit, :archive], group_sortable: true}