config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}

  root to: 'static#index'

  get :dashboard, to: 'dashboard#index'

  resource :user, only: [:edit, :update]

  resources :todo_lists, path: 'todos' do
    collection do
      get :archived
      get :plan
    end

    member do
      put :sort, constraints: {format: :json}
      put :archive
      put :restore
    end
  end
end

app/views/layouts/_flash_message.slim
- messages = []
- if defined? message
  - messages << message if message.is_a? String
  - messages += message if message.is_a? Array
- messages.each do |msg|
  div(uk-alert class=(translate_flash_type type))
    a.uk-alert-close(uk-close)
    p= msg

app/views/layouts/_navigation.slim
nav.uk-navbar-container(role="navigation" uk-navbar)
  .uk-navbar-left
    ul.uk-navbar-nav
      li= link_to t('page.layout.title'), root_path, class: 'page-title'
      li= link_to t('page.layout.dashboard'), dashboard_path
      li= link_to t('page.layout.list'), todo_lists_path
      li= link_to t('page.layout.plan'), plan_todo_lists_path
      li= link_to t('page.layout.archive'), archived_todo_lists_path
  .uk-navbar-right
    ul.uk-navbar-nav
      - if user_signed_in?
        li.uk-parent
          = link_to current_user.email, edit_user_path
          .uk-navbar-dropdown
            ul.uk-nav.uk-navbar-dropdown-nav
              li=link_to t('page.layout.edit_profile'), edit_user_path
              li=link_to t('page.layout.logout'), destroy_user_session_path, method: :delete
      - else
        li=link_to t('page.layout.login'), new_user_session_path

app/views/layouts/application.slim
doctype html
html lang=I18n.locale dir="ltr"
  head
    meta charset="utf-8"

    // Instruct IE to use its latest rendering engine
    meta http-equiv="x-ua-compatible" content="ie=edge"

    meta name="viewport" content="width=device-width, initial-scale=1"

    title Todo

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    header role="banner"
      = render partial: 'layouts/navigation'
    main.uk-container role="main"
      - if @time_zone_missing
        = render partial: 'layouts/flash_message', locals: {type: :alert, message: "#{t 'page.layout.missing_time_zone'} #{link_to t('page.layout.edit_profile'), edit_user_path}".html_safe}
      - flash.each do |k, msg|
        = render partial: 'layouts/flash_message', locals: {type: k, message: msg}
      = yield